FROM golang:1.24-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /nydus-worm ./cmd/worm/

FROM alpine:3.20
RUN apk add --no-cache git curl docker-cli docker-cli-compose && \
    git config --global --add safe.directory '*'
WORKDIR /app
COPY --from=builder /nydus-worm .
COPY configs/worm.yaml ./configs/
EXPOSE 8096
CMD ["./nydus-worm"]
