package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// ════════════════════════════════════════════════════════════════
//  Forge — AI-Native Project Management for Claw
// ════════════════════════════════════════════════════════════════

// ForgeProject represents a project in the Claw Forge system.
// A project belongs to a Squad (team) and links to a Nydus repo.
type ForgeProject struct {
	ID          string    `json:"id" gorm:"type:varchar(36);primaryKey"`
	Name        string    `json:"name" gorm:"type:varchar(200);not null"`
	Description string    `json:"description" gorm:"type:text"`
	SquadID     string    `json:"squad_id" gorm:"type:varchar(36);index"`          // owning squad/team
	UserID      string    `json:"user_id" gorm:"type:varchar(36);index;not null"`  // creator
	NydusRepo   string    `json:"nydus_repo" gorm:"type:varchar(100)"`             // linked Nydus repo name
	Status      string    `json:"status" gorm:"type:varchar(20);default:active"`   // active / archived
	Visibility  string    `json:"visibility" gorm:"type:varchar(20);default:team"` // public / team / private
	Tags        string    `json:"tags" gorm:"type:varchar(500)"`                   // comma-separated
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (p *ForgeProject) BeforeCreate(tx *gorm.DB) error {
	if p.ID == "" {
		p.ID = uuid.New().String()
	}
	return nil
}

// ForgeIssue represents a task/bug/feature request in the Forge.
// Issues are the core work item, assignable to Claw nodes (AI agents).
type ForgeIssue struct {
	ID          string     `json:"id" gorm:"type:varchar(36);primaryKey"`
	ProjectID   string     `json:"project_id" gorm:"type:varchar(36);index;not null"`
	Number      int        `json:"number" gorm:"index"`                                    // project-scoped issue number
	Title       string     `json:"title" gorm:"type:varchar(500);not null"`
	Body        string     `json:"body" gorm:"type:text"`
	Type        string     `json:"type" gorm:"type:varchar(20);default:task"`              // task / bug / feature / epic
	Priority    string     `json:"priority" gorm:"type:varchar(20);default:medium"`        // critical / high / medium / low
	Status      string     `json:"status" gorm:"type:varchar(20);default:open;index"`      // open / in_progress / review / done / closed
	AssigneeNode string    `json:"assignee_node" gorm:"type:varchar(80);index"`            // claw:xxx or ai:role
	ReporterNode string    `json:"reporter_node" gorm:"type:varchar(80)"`                  // who created
	MilestoneID string     `json:"milestone_id" gorm:"type:varchar(36);index"`
	SprintID    string     `json:"sprint_id" gorm:"type:varchar(36);index"`                // linked sprint
	MissionID   string     `json:"mission_id" gorm:"type:varchar(36);index"`               // linked squad mission
	PRNumber    int        `json:"pr_number" gorm:"default:0"`                             // linked PR on Nydus
	Branch      string     `json:"branch" gorm:"type:varchar(100)"`                        // working branch
	Labels      string     `json:"labels" gorm:"type:varchar(500)"`                        // comma-separated
	StoryPoints int        `json:"story_points" gorm:"default:0"`
	DueDate     *time.Time `json:"due_date"`
	ClosedAt    *time.Time `json:"closed_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

func (i *ForgeIssue) BeforeCreate(tx *gorm.DB) error {
	if i.ID == "" {
		i.ID = uuid.New().String()
	}
	return nil
}

// ForgeIssueComment is a comment on an issue (by human or AI agent).
type ForgeIssueComment struct {
	ID         string    `json:"id" gorm:"type:varchar(36);primaryKey"`
	IssueID    string    `json:"issue_id" gorm:"type:varchar(36);index;not null"`
	AuthorNode string    `json:"author_node" gorm:"type:varchar(80)"` // claw:xxx or ai:reviewer
	Body       string    `json:"body" gorm:"type:text;not null"`
	IsAI       bool      `json:"is_ai" gorm:"default:false"` // true if generated by AI
	CreatedAt  time.Time `json:"created_at"`
}

func (c *ForgeIssueComment) BeforeCreate(tx *gorm.DB) error {
	if c.ID == "" {
		c.ID = uuid.New().String()
	}
	return nil
}

// ForgeMilestone groups issues into a release target.
type ForgeMilestone struct {
	ID          string     `json:"id" gorm:"type:varchar(36);primaryKey"`
	ProjectID   string     `json:"project_id" gorm:"type:varchar(36);index;not null"`
	Title       string     `json:"title" gorm:"type:varchar(200);not null"`
	Description string     `json:"description" gorm:"type:text"`
	DueDate     *time.Time `json:"due_date"`
	Status      string     `json:"status" gorm:"type:varchar(20);default:open"` // open / closed
	ClosedAt    *time.Time `json:"closed_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

func (m *ForgeMilestone) BeforeCreate(tx *gorm.DB) error {
	if m.ID == "" {
		m.ID = uuid.New().String()
	}
	return nil
}

// ForgeBoard represents a Kanban-style board view for a project.
type ForgeBoard struct {
	ID        string    `json:"id" gorm:"type:varchar(36);primaryKey"`
	ProjectID string    `json:"project_id" gorm:"type:varchar(36);index;not null"`
	Name      string    `json:"name" gorm:"type:varchar(100);not null"`
	Columns   string    `json:"columns" gorm:"type:text"` // JSON array of column configs: [{"name":"Todo","status":"open"},...]
	IsDefault bool      `json:"is_default" gorm:"default:false"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (b *ForgeBoard) BeforeCreate(tx *gorm.DB) error {
	if b.ID == "" {
		b.ID = uuid.New().String()
	}
	return nil
}
