"""
Base Strategy — all trading strategies inherit from this class.
"""

import logging
from abc import ABC, abstractmethod
from typing import Dict, List, Optional

logger = logging.getLogger("strategy")


class Signal:
    """A trading signal generated by a strategy."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"

    def __init__(self, code: str, direction: str, price: float = 0, volume: int = 0,
                 reason: str = "", confidence: float = 0.0):
        self.code = code
        self.direction = direction
        self.price = price
        self.volume = volume
        self.reason = reason
        self.confidence = confidence  # 0.0 - 1.0

    def __repr__(self):
        return f"Signal({self.direction} {self.code} @{self.price} x{self.volume} [{self.confidence:.0%}] {self.reason})"


class BaseStrategy(ABC):
    """
    Base class for all quantitative trading strategies.

    Lifecycle:
        1. __init__(params) — configure strategy parameters
        2. on_init() — called once when strategy starts
        3. on_bar(code, bar) — called on each new K-line bar
        4. on_tick(code, tick) — called on each real-time tick (optional)
        5. on_order_filled(order) — called when an order is filled
        6. on_stop() — called when strategy stops

    Subclasses must implement:
        - on_bar() — core strategy logic
    """

    def __init__(self, strategy_id: str, account: str, params: Dict = None):
        self.strategy_id = strategy_id
        self.account = account
        self.params = params or {}
        self.positions: Dict[str, int] = {}  # code → volume
        self.signals: List[Signal] = []
        self._running = False

    @property
    def name(self) -> str:
        return self.__class__.__name__

    def on_init(self):
        """Called once when the strategy starts. Override for initialization."""
        pass

    @abstractmethod
    def on_bar(self, code: str, bar: dict) -> Optional[Signal]:
        """
        Called on each new K-line bar.

        Args:
            code: Stock code (e.g. '600519.SH')
            bar: Dict with keys: date, open, high, low, close, volume, amount

        Returns:
            Signal or None
        """
        pass

    def on_tick(self, code: str, tick: dict) -> Optional[Signal]:
        """Called on each real-time tick. Override for tick-level strategies."""
        return None

    def on_order_filled(self, order: dict):
        """Called when an order is filled. Update internal positions."""
        code = order.get("code", "")
        volume = order.get("volume", 0)
        direction = order.get("direction", "")

        if direction == "buy":
            self.positions[code] = self.positions.get(code, 0) + volume
        elif direction == "sell":
            self.positions[code] = self.positions.get(code, 0) - volume
            if self.positions.get(code, 0) <= 0:
                self.positions.pop(code, None)

        logger.info(f"[{self.name}] order filled: {direction} {code} x{volume}, positions: {self.positions}")

    def on_stop(self):
        """Called when the strategy stops. Override for cleanup."""
        pass

    def start(self):
        self._running = True
        self.on_init()
        logger.info(f"[{self.name}] started on {self.account}")

    def stop(self):
        self._running = False
        self.on_stop()
        logger.info(f"[{self.name}] stopped")

    @property
    def is_running(self) -> bool:
        return self._running
