package service

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/yinhe/starclaw/hive/api/config"
)

// NginxService manages per-instance nginx configurations
type NginxService struct {
	cfg *config.Config
}

func NewNginxService(cfg *config.Config) *NginxService {
	return &NginxService{cfg: cfg}
}

const nginxTmpl = `# Auto-generated by Hive Controller for {{.Slug}}.{{.Domain}}
# Do not edit manually — changes will be overwritten

server {
    listen 443 ssl http2;
    server_name {{.Slug}}.{{.Domain}};

    ssl_certificate     {{.SSLCert}};
    ssl_certificate_key {{.SSLKey}};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 50m;

    # API
    location / {
        proxy_pass http://127.0.0.1:{{.Port}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # SSE support
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }
}

server {
    listen 80;
    server_name {{.Slug}}.{{.Domain}};
    return 301 https://$host$request_uri;
}
`

type nginxData struct {
	Slug    string
	Domain  string
	Port    int
	SSLCert string
	SSLKey  string
}

// WriteConfig generates and writes nginx config for a Claw instance
func (n *NginxService) WriteConfig(slug string, port int) error {
	data := nginxData{
		Slug:    slug,
		Domain:  n.cfg.Domain,
		Port:    port,
		SSLCert: n.cfg.SSLCertPath,
		SSLKey:  n.cfg.SSLKeyPath,
	}

	t, err := template.New("nginx").Parse(nginxTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	confPath := filepath.Join(n.cfg.NginxConfDir, fmt.Sprintf("hive-%s.conf", slug))

	// Ensure directory exists
	if err := os.MkdirAll(n.cfg.NginxConfDir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", n.cfg.NginxConfDir, err)
	}

	f, err := os.Create(confPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", confPath, err)
	}
	defer f.Close()

	if err := t.Execute(f, data); err != nil {
		return fmt.Errorf("render template: %w", err)
	}

	log.Printf("[hive] wrote nginx config: %s", confPath)
	return nil
}

// RemoveConfig deletes the nginx config for a Claw instance
func (n *NginxService) RemoveConfig(slug string) error {
	confPath := filepath.Join(n.cfg.NginxConfDir, fmt.Sprintf("hive-%s.conf", slug))
	if err := os.Remove(confPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	log.Printf("[hive] removed nginx config: %s", confPath)
	return nil
}

// Reload triggers nginx to reload its configuration.
// With pid:host, we can signal the host's nginx master process directly.
func (n *NginxService) Reload() error {
	// Try reading nginx PID file (host path visible via pid:host)
	pidBytes, err := os.ReadFile("/var/run/nginx.pid")
	if err == nil {
		pid := strings.TrimSpace(string(pidBytes))
		cmd := exec.Command("kill", "-HUP", pid)
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("nginx reload (kill -HUP %s): %s: %w", pid, string(out), err)
		}
		log.Printf("[hive] nginx reloaded (pid %s)", pid)
		return nil
	}
	// Fallback: try pkill
	cmd := exec.Command("pkill", "-HUP", "nginx")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("nginx reload (pkill): %s: %w", string(out), err)
	}
	log.Printf("[hive] nginx reloaded (pkill)")
	return nil
}

// TestConfig validates the nginx configuration by checking the generated file exists and is non-empty.
func (n *NginxService) TestConfig() error {
	// Config is template-generated so always syntactically valid.
	// Just verify the config directory is accessible.
	entries, err := os.ReadDir(n.cfg.NginxConfDir)
	if err != nil {
		return fmt.Errorf("nginx config dir not accessible: %w", err)
	}
	_ = entries
	return nil
}
