linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gosimple

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters: [staticcheck]
      text: "SA1019.*strings.Title"
    - linters: [staticcheck]
      text: "SA4010"
    - linters: [gosimple]
      text: "S1000"
    - linters: [gosimple]
      text: "S1011"
